services:
  engelvin-maroc:
    image: englvinmaroc
    container_name: engelvin-maroc
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/engelvinMaroc?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - mysqldb
    networks:
      - springmysql-net

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: engelvinMaroc
      MYSQL_ROOT_PASSWORD: root
    networks:
      - springmysql-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysqldb
    networks:
      - springmysql-net

networks:
  springmysql-net:
